### ISSUE TITLE
Succesfully used caer from remote connection to a server

### ISSUE THREAD

**Issue by sanfans** [inilabs/caer#130]
I was succesfully able to connect from Ubuntu subsystem in Windows 10 (https://msdn.microsoft.com/en-us/commandline/wsl/install-win10) to zemo server and run cAER on the  DYNAP-se connected to it.
Unfortunately Ubuntu on W10 is not able by default to display GUI applications, but returns the error "Can't connect to display". Following this guide:
https://askubuntu.com/questions/823352/windows-10-bash-cannot-connect-to-display
i solved the problem installing an X server on windows (Xming), that can be found here: 
https://sourceforge.net/projects/xming/?source=typ_redirect)
To test if it worked, i just typed in the Ubuntu terminal:
* export DISPLAY=:0
* xclock

Succesfully the clock appeared.
Then i decided to test if i could now connect with ssh -X to zemo server and display on my windows PC a remote GUI application (i couldn't do it before).
I connected to the server and ran xclock, but i got this error:
* Error: Can't open display: zemo:11.0

Following this guide:
https://unix.stackexchange.com/questions/57138/why-does-my-x11-forwarding-attempt-fail-with-connect-tmp-x11-unix-x0-no-such
I just typed, on the CONNECTING pc (so i logged out from zemo), instead of "export DISPLAY=:0":
* export DISPLAY=localhost:0.0

That worked for me. I was succesfully able to run xclock from remote (also gedit, etc.)
The last step was to try to run cAER from remote. I was succesfully able to do it, with an incredible slowness caused probably by the wifi connection. Still it worked, as can be seen from the image below:

![example_caer_remote](https://user-images.githubusercontent.com/15872256/33480015-9d61dd42-d68f-11e7-9b3d-80badbfb7561.JPG)

This means that the problem of using remotely cAER has nothing to do with ssh, but must be searched among other possible causes.
Still there were different warnings and strange errors, that i post below.

WHEN CONNECTING REMOTELY USING SSH -X:
* Warning: No xauth data; using fake authentication data for X11 forwarding.

WHEN RUNNING cAER:
* An internal OpenGL call failed in Texture.cpp(154).
Expression:
   glGenTextures(1, &texture)
Error description:
   GL_INVALID_OPERATION
   The specified operation is not allowed in the current state.
* An internal OpenGL call failed in TextureSaver.cpp(38).
Expression:
   glGetIntegerv(GL_TEXTURE_BINDING_2D, &m_textureBinding)
Error description:
   GL_INVALID_OPERATION
   The specified operation is not allowed in the current state.
* An internal OpenGL call failed in Texture.cpp(181).
Expression:
   glBindTexture(GL_TEXTURE_2D, m_texture)
Error description:
   GL_INVALID_OPERATION
   The specified operation is not allowed in the current state.
* An internal OpenGL call failed in Texture.cpp(182).
Expression:
   glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, m_actualSize.x, m_actualSize.y, 0, GL_RGBA, GL_UNSIGNED_BYTE, NULL)
Error description:
   GL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

WHEN RUNNING JAVA GUI:
* ES2 Prism: Error - reported GLX version = 1.2
    GLX version 1.3 or higher is required

**Comment by llongi** [comment]
Well, OpenGL (which both the cAER visualizer and the JavaFX GUI internally use) over SSH is not well supported, it _can_ work because the GLX protocol in theory supports sending the OpenGL rendering commands to the remote PC, but this is super-slow, which you already noticed, and depends a lot on having very compatible graphics cards and drivers on both ends, as the program started remotely may assume things about its graphics environment from the local driver which are just not true on the remote one. This kind of disparity and incompatibility would only be exacerbated by using Windows10+beta Ubuntu subsystem.
This configuration is not supported at all by us.
cAER was designed with running remotely in mind, but not in this way.
If you need to visualize data, configure the remote cAER to output its data stream via network, and then start a cAER on your local computer, configured to take its input from the network and visualize it.
If you need to configure a cAER instance (caerctl-gui-javafx or caer-ctl CLI), they specifically support remote connection: just type in the right IP and port in the very first screen that you are presented with. You also will need to change the configuration on the remote cAER to allow external connections to the configuration subsystem, open caer-config.xml and search for the /caer/server/ node:

```
<node name="server" path="/caer/server/">
                <attr key="ipAddress" type="string">127.0.0.1</attr>
                <attr key="portNumber" type="int">4040</attr>
</node>
```

There, change the IP address to either the external IP of that system, or to 0.0.0.0 to listen on all available interfaces.
