### ISSUE TITLE
network input from caer 

### ISSUE THREAD

**Issue by sanfans** [inilabs/caer#131]
Hi, 

I am trying to have cAER reading network inputs from a remote computer in which there is cAER running with a Dynap-se board.

I can set in the remote machine the "caer_output_net_tcp_server" so that the events are streamed via network. However, in my local machine, I have a problem when configuring the visualizer with the "caer_input_net_tcp_client" module.

Here the caer-config.xml for my local machine..

<sshs version="1.0">
    <node name="" path="/">
        <node name="caer" path="/caer/">
            <node name="logger" path="/caer/logger/">
                <attr key="logFile" type="string">/home/roberto/GitHub/caer/caer.log</attr>
                <attr key="logLevel" type="byte">5</attr>
            </node>
            <node name="modules" path="/caer/modules/">
                <attr key="modulesSearchPath" type="string">/home/roberto/GitHub/caer/modules/|/usr/local/share/caer/modules/</attr>
            </node>
            <node name="server" path="/caer/server/">
                <attr key="ipAddress" type="string">127.0.0.1</attr>
                <attr key="portNumber" type="int">4040</attr>
            </node>
        </node>
        <node name="networkinput" path="/networkinput/">
            <attr key="moduleId" type="short">2</attr>
            <attr key="moduleLibrary" type="string">caer_input_net_tcp_client</attr>
            <attr key="moduleOutput" type="string">1</attr>
        </node>
        <node name="visualizer" path="/visualizer/">
            <attr key="moduleId" type="short">1</attr>
            <attr key="moduleInput" type="string">2[12]</attr>
            <attr key="moduleLibrary" type="string">caer_visualizer</attr>
        </node>
    </node>
</sshs>

when I start caer I see the following error.

2017-12-05 12:24:25 (TZ+0100): NOTICE: Mainloop: 2 modules found.
2017-12-05 12:24:25 (TZ+0100): ERROR: Mainloop: Module 'visualizer': Invalid 'moduleInput' attribute: Unknown event stream.
2017-12-05 12:24:25 (TZ+0100): CRITICAL: Mainloop: Failed to start mainloop, please fix the configuration and try again!

any ideas of what I might be doing wrong?
thank you!

**Comment by llongi** [comment]
Hi, I believe the problem here is that you didn't specify what kind of data the network input module generates.
If you go to the Network Input module's configuration, you'll notice an attribute named 'moduleOutput', and that is probably empty.
Some input modules, like the file or the network ones, are generic, meaning they can in theory read and output any kind of event. In order for cAER to build the connectivity between modules and verify its correctness, it needs to know which events these modules will generate at runtime. For such modules, that is configured in the 'moduleOutput' attribute, a comma separated list of event type IDs. So in your case, where you want to get Spike events from the remote system, just set it to '12'. After that the visualizer should be able to get the events from it.
