### ISSUE TITLE
Help transmission to v2.4: how get event from FrameEventPacket C++?

### ISSUE THREAD

**Issue by breznak** [inilabs/caer#136]
Hello, 
I'm upgrading my code to upstream version 2.4 of libcaer. I'm running into an Issue with FrameEvent: 

My code used to do this to loop all evts in a packet: 
>   FrameEventPacket framePacket = FrameEventPacket((caerFrameEventPacket)packet.data(), false);
 for(auto evt : framePacket) {

Now I get message with deleted constructor: 
>  error: call to deleted constructor of 'libcaer::events::FrameEvent'
  for(auto evt : framePacket) {
           ^   ~
/usr/local/include/libcaercpp/events/frame.hpp:27:2: note: 'FrameEvent' has been explicitly marked deleted here
        FrameEvent(const FrameEvent &rhs) = delete;

How am I supposed to loop through FrameEvents in the packet, please? In c++

**Comment by llongi** [comment]
If you have a C++ FrameEventPacket, the best way is to just loop over it:

```
for (const auto &frame : frames) {
   ...
}
```

The constructor was deleted because there's no safe way to copy a frame over automatically, you have to use the copy() functions.
But to just loop over frames you don't need a copy, for performance actually you don't want a copy, so just use a reference.

**Comment by breznak** [comment]
Thank you!
