### ISSUE TITLE
On Linux, if display video, how make caer? And run which application?

### ISSUE THREAD

**Issue by mrunix** [inilabs/caer#39]
Like jAER.

**Comment by federicohyo** [comment]
Dear Michael,

In caer you should be able to record an output aedat file by enabling the outputmodule.. when you compile you should use the flags:

$ cmake -DDVS128=1 -DENABLE_VISUALIZER=1 -DENABLE_STATISTICS=1 -DENABLE_FILE_OUTPUT=1 .

then when you run caer you can start and stop the recordings using ./utils/caerctl/caer-ctl (or use the javaFX2 GUI) https://github.com/inilabs/caerctl-gui-javafx.

Once you are done with the recordings and you want to play it back. 

You can compile (or have it compiled already) a caer version with the input module instead of the DVS128..when you compile you should use the flags:

$ cmake -DENABLE_FILE_INPUT=1 -DENABLE_VISUALIZER=1 -DENABLE_STATISTICS=1 -DENABLE_FILE_OUTPUT=1 .

and set the options of the file to be played by using caer-ctl or the javaFX2 gui

Sorry it might sound a bit complicated but cAER is meant to be optimized for embedded platforms and it is currently being developed.
