### ISSUE TITLE
Compilation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by duguyue100** [inilabs/caer#43]
Hi,

I was compiling caer using Ubuntu 16.04, `gcc` version is 5.4.0. And the `cmake` configuration is `

```
cmake -DDAVISFX2=1 -DENABLE_NETWORK_OUTPUT=1  -DENABLE_NETWORK_INPUT=1 -DENABLE_VISUALIZER=0 -DENABLE_STATISTICS=1 .
```

Then the error is occurred at

```
[ 69%] Building C object CMakeFiles/caer-bin.dir/main.c.o
/home/yang/workspace/caer-temp/main.c: In function ‘mainloop_1’:
/home/yang/workspace/caer-temp/main.c:148:23: error: redefinition of ‘frame’
  caerFrameEventPacket frame = NULL;
                       ^
/home/yang/workspace/caer-temp/main.c:125:23: note: previous definition of ‘frame’ was here
  caerFrameEventPacket frame = NULL;
                       ^
/home/yang/workspace/caer-temp/main.c:149:22: error: redefinition of ‘imu’
  caerIMU6EventPacket imu = NULL;
                      ^
/home/yang/workspace/caer-temp/main.c:126:22: note: previous definition of ‘imu’ was here
  caerIMU6EventPacket imu = NULL;
                      ^
CMakeFiles/caer-bin.dir/build.make:638: recipe for target 'CMakeFiles/caer-bin.dir/main.c.o' failed
make[2]: *** [CMakeFiles/caer-bin.dir/main.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caer-bin.dir/all' failed
make[1]: *** [CMakeFiles/caer-bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

The problem is that the variables `imu` and `frame` are redefined in line148-149 at `main.c` while both `NETWORK_OUTPUT` and `DAVISFX2` are enabled. Apparently this is not allowed in `gcc` 5.4.

I commented line 148 and 149, and the compilation was finished without error.

**Comment by federicohyo** [comment]
Hi,

Yes that is correct. You should enable only one input a time. The readme
specify that too. Network input and input from the camera are not allowed
at the same time (at least with the current main.c example).


I hope this clarify it


With best regards,
Federico






Il 05/gen/2017 11:01 PM, "Yuhuang Hu" <notifications@github.com> ha scritto:

Hi,

I was compiling caer using Ubuntu 16.04, gcc version is 5.4.0. And the cmake
configuration is `

cmake -DDAVISFX2=1 -DENABLE_NETWORK_OUTPUT=1  -DENABLE_NETWORK_INPUT=1
-DENABLE_VISUALIZER=0 -DENABLE_STATISTICS=1 .

Then the error is occurred at

[ 69%] Building C object CMakeFiles/caer-bin.dir/main.c.o
/home/yang/workspace/caer-temp/main.c: In function ‘mainloop_1’:
/home/yang/workspace/caer-temp/main.c:148:23: error: redefinition of ‘frame’
  caerFrameEventPacket frame = NULL;
                       ^
/home/yang/workspace/caer-temp/main.c:125:23: note: previous
definition of ‘frame’ was here
  caerFrameEventPacket frame = NULL;
                       ^
/home/yang/workspace/caer-temp/main.c:149:22: error: redefinition of ‘imu’
  caerIMU6EventPacket imu = NULL;
                      ^
/home/yang/workspace/caer-temp/main.c:126:22: note: previous
definition of ‘imu’ was here
  caerIMU6EventPacket imu = NULL;
                      ^
CMakeFiles/caer-bin.dir/build.make:638: recipe for target
'CMakeFiles/caer-bin.dir/main.c.o' failed
make[2]: *** [CMakeFiles/caer-bin.dir/main.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caer-bin.dir/all' failed
make[1]: *** [CMakeFiles/caer-bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

The problem is that the variables imu and frame are redefined in
line148-149 at main.c while both NETWORK_OUTPUT and DAVISFX2 are enabled.
Apparently this is not allowed in gcc 5.4.

I tried to comment line 148 and 149, and the compilation is finished
without error.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/inilabs/caer/issues/43>, or mute the thread

**Comment by duguyue100** [comment]
Right, I wrongly modified the instruction in the iniLabs manual.
Thanks.

**Comment by duguyue100** [comment]
Wait... I think I wrongly explained the problem.

the related code is here

```c
#if defined(DAVISFX2) || defined(DAVISFX3)
	// Typed EventPackets contain events of a certain type.
	special = (caerSpecialEventPacket) caerEventPacketContainerGetEventPacket(container, SPECIAL_EVENT);
	polarity = (caerPolarityEventPacket) caerEventPacketContainerGetEventPacket(container, POLARITY_EVENT);

	// Frame and IMU events exist only with DAVIS cameras.
	caerFrameEventPacket frame = NULL;
	caerIMU6EventPacket imu = NULL;

	frame = (caerFrameEventPacket) caerEventPacketContainerGetEventPacket(container, FRAME_EVENT);
	imu = (caerIMU6EventPacket) caerEventPacketContainerGetEventPacket(container, IMU6_EVENT);
#endif

#if defined(ENABLE_FILE_INPUT) || defined(ENABLE_NETWORK_INPUT)
#ifdef ENABLE_VISUALIZER
	visualizerEventHandler = &caerInputVisualizerEventHandler;
#endif

	// Typed EventPackets contain events of a certain type.
	// We search for them by type here, because input modules may not have all or any of them.
	special = (caerSpecialEventPacket) caerEventPacketContainerFindEventPacketByType(container, SPECIAL_EVENT);
	polarity = (caerPolarityEventPacket) caerEventPacketContainerFindEventPacketByType(container, POLARITY_EVENT);

	caerFrameEventPacket frame = NULL;
	caerIMU6EventPacket imu = NULL;

	frame = (caerFrameEventPacket) caerEventPacketContainerFindEventPacketByType(container, FRAME_EVENT);
	imu = (caerIMU6EventPacket) caerEventPacketContainerFindEventPacketByType(container, IMU6_EVENT);
#endif
```

Isn't this saying that if I turned up both `DAVISFX2` and some input mode, then the `frame` and `imu` will be redefined?

And in my previous setting, I only turned on network input and output.

**Comment by federicohyo** [comment]
Hi,

Only one input mode can be active: OR the input from the camera OR one
other input mode. To better explain the error I have explicitely added an
error message during compilation, see:
https://github.com/inilabs/caer/commit/ec8480189d94a9c22330e81bcf62eed14da0cc64

best,
 Federico


electronically yours,
 Federico
