### ISSUE TITLE
working with DAVIS640 and 240?

### ISSUE THREAD

**Issue by Thanh-Binh** [inilabs/caer#54]
In my laptop, I can work only with Davis640.
After compiling for davis240
cmake -DDAVISFX2=1 -DENABLE_BAFILTER=1 -DENABLE_VISUALIZER=1 . && make -j8 
and run the program " ./caer-bin-davis240", but I have only errors like:
 2017-03-20 14:23:38 (TZ+0100): NOTICE: Logger: Initialization successful with log-level 5.
2017-03-20 14:23:38 (TZ+0100): CRITICAL: davisCommonOpen: Failed to open DAVIS FX3 device.
2017-03-20 14:23:39 (TZ+0100): CRITICAL: davisCommonOpen: Failed to open DAVIS FX3 device.
Total events/second:          0 - Valid events/second:          02017-03-20 14:23:41 (TZ+0100): CRITICAL: davisCommonOpen: Failed to open DAVIS FX3 device.

I do not know why it tried to open DAVIS FX3 device.
What should I do?

**Comment by federicohyo** [comment]
Hi Bihn,

try to remove the CMakeFiles/ folder and the CMakeCache.txt file.
The problem is that cmake keeps track of the old preferences you have selected.

just run

rm -rf CMakeCache.txt CMakeFiles/
cmake -DDAVISFX2=1 -DENABLE_BAFILTER=1 -DENABLE_VISUALIZER=1 . && make -j8

or equivalently (set to zero the DAVISFX3 device)
cmake -DDAVISFX2=1 -DDAVISFX3=0 -DENABLE_BAFILTER=1 -DENABLE_VISUALIZER=1 . && make -j8

let me know it this helps.
